import numpy as np
arr_int = np.array([[1, 2, 3], dtype='int'])
print("integer dtype",arr_int.dtype)
arr_float = np.array([[1, 2, 3], dtype='float32'])
arr_bool = np.array([[1, 0, 1], dtype='bool'])
print("boolean dtype :", arr_bool.dtype)
arr_complex = np.array([[1+2j, 3+4j], dtype=np.complex64])
print("complex dtype :", arr_complex.dtype)
arr_string = np.array([['hello', 'world'], dtype='str'])
print("string dtype :", arr_string.dtype)
arr_unicode = np.array([['hello', 'world'], dtype='U'])
print("unicode dtype :", arr_unicode.dtype)
arr = np.array([[1, 2, 3], dtype='float32'])
print("given array dtype:", arr.dtype)